---
- name: Clone a github repository {{ azure_vm_tf_source|basename }}
  git:
    repo: '{{ azure_vm_tf_source }}'
    dest: '{{ azure_vm_tf_module_download_path }}'
    clone: yes
    update: yes
    version: main

 