---
- name: Rhel VM creation
  community.general.terraform:
    project_path: '{{ azure_vm_tf_module_download_path }}'
    state: '{{ rhel_vm_state }}'
    force_init: true 
    complex_vars: true 
    variables:
      azurerm_resource_group_name: '{{ azurerm_resource_group_name }}'
      azurerm_virtual_network_name: '{{ azurerm_virtual_network_name }}'
      virtual_network_resource_group_name: '{{ virtual_network_resource_group_name }}'
      azurerm_subnet_name: '{{ azurerm_subnet_name }}'
      admin_password: '{{ admin_password }}'
      source_image_reference_offer: '{{ source_image_reference_offer }}'
      source_image_reference_sku: '{{ source_image_reference_sku }}'
      source_image_reference_publisher: '{{ source_image_reference_publisher }}'
      source_image_reference_version: '{{ source_image_reference_version }}'
      priority: '{{ priority }}'
      max_bid_price: '{{ max_bid_price }}'
      eviction_policy: '{{ eviction_policy }}'
      tags: '{{ tags }}'
  register: rhel_vm_output
  
- debug:
    var: rhel_vm_output
