namespace: intel
name: ansible_intel_azure_linux_vm
version: 1.0.0
readme: README.md
authors:
  - Akhil D <akhil.d@intel.com>
description: This module will create new Azure virtual machine, The instance is pre-configured with parameters.
tags:
  - ansible
  - aws
  - vm
repository: 'https://github.com/OTCShare2/ansible-intel-azure-linux-'
