---
# tasks file for azure_rhel_vm_multi_disks
- name: Download module
  ansible.builtin.include_tasks:
    file: download_tf_module.yml
  when: rhel_vm_state == "present"

- name: VM configure
  ansible.builtin.include_tasks:
    file: vm.yml

- name: managed disk
  ansible.builtin.include_tasks:
    file: managed_disk.yml

- name: Output
  ansible.builtin.include_tasks:
    file: output.yml
  when: rhel_vm_state == "present"