- set_fact:
    managed_by_extended:
      - resource_group: '{{ azurerm_resource_group_name }}'
        name: '{{ vm_name }}'
  when: rhel_vm_disk_state == 'present' or (rhel_vm_disk_state == 'absent' and rhel_vm_state == 'present')

- debug:
    var: managed_by_extended

- name: Azure managed disk
  azure.azcollection.azure_rm_multiplemanageddisks:
    tags: '{{ disk_tags }}'
    state: '{{ rhel_vm_disk_state }}'
    managed_disks:
      - name: '{{ disk_name }}'
        resource_group: '{{ disk_resource_group_name }}'
        storage_account_type: '{{ storage_account_type }}'
        location: '{{ location }}'
        create_option: '{{ create_option }}'
        disk_size_gb: '{{ disk_size_gb }}'
        lun: '{{ lun }}'
        attach_caching: '{{ caching }}'
    managed_by_extended: '{{ managed_by_extended }}'
  register: managed_disk_output
- debug:
    var: managed_disk_output

- name: Detach managed disks from all VMs and delete it
  azure.azcollection.azure_rm_multiplemanageddisks:
    state: absent
    managed_disks:
      - name: '{{ disk_name }}'
        resource_group: '{{ disk_resource_group_name }}'
  when: rhel_vm_disk_state == 'absent'

