---
- name: create azure managed disk
  azure_rm_manageddisk:
    state: '{{ vm_state }}'
    name: '{{ disk_name }}'
    resource_group: '{{ resource_group_name }}'
    storage_account_type: '{{ storage_account_type }}'
    location: '{{ location }}'
    create_option: '{{ create_option }}'
    disk_size_gb: '{{ disk_size_gb }}'
    tags:
      owner: '{{ owner }}'
      duration: '{{ duration }}'
  register: managed_disk_output