---
- name: Create Azure managed disk
  azure_rm_multiplemanageddisks:
    managed_disks:
      state: '{{ rhel_vm_state }}'
      name: '{{ disk_name }}'
      resource_group: '{{ resource_group_name }}'
      storage_account_type: '{{ storage_account_type }}'
      location: '{{ location }}'
      create_option: '{{ create_option }}'
      disk_size_gb: '{{ disk_size_gb }}'
      tags: '{{ tags }}'
      lun: '{{ lun }}'
      attach_caching: '{{ caching }}'
    managed_by_extended:
      - resource_group: '{{ azurerm_resource_group_name }}'
        name: TestVM
  register: managed_disk_output
- debug:
    var: managed_disk_output

