---
- name: Run azure_rhel_vm_multi_disks role
  hosts: localhost
  tasks:
    - name: Running a role Azure linux vm multi disks
      ansible.builtin.import_role:
        name: azure_rhel_vm_multi_disks
      vars:
        rhel_vm_state: present
        rhel_vm_disk_state: present
        azurerm_resource_group_name: "<azurerm_resource_group_name>"
        azurerm_virtual_network_name: "vnet1"
        virtual_network_resource_group_name: "<virtual_network_resource_group_name>"