---
- name: Run azure_rhel_vm_spot_vm role
  hosts: localhost
  tasks:
    - name: Running a role Azure rhel vm spot vm
      ansible.builtin.import_role:
        name: azure_rhel_vm_spot_vm
      vars:
        rhel_vm_state: present
        azurerm_resource_group_name: "<azurerm_resource_group_name>"
        azurerm_virtual_network_name: "vnet1"
        virtual_network_resource_group_name: "<virtual_network_resource_group_name>"